version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plateforme_signalement_suivi
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  webapp:
    build: .
    container_name: plateforme_signalement
    depends_on:
      - mysql
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=plateforme_signalement_suivi
      - DB_USER=root
      - DB_PASSWORD=root
    volumes:
      - .:/usr/local/tomcat/webapps/

volumes:
  db_data: